title: Ambar Mendez
description: "My simple GitHub page"
author:
  name: "Ambar Mendez"
  email: "ambarmendez@gmail.com"
  url: "https://ambarmendez.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
google_analytics : UA-178996274-1
owner : "SomeHacker"
year : "2020"
